apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: iot-cloud-webhook
spec:
  secretName: iot-cloud-webhook-tls-certificate
  issuerRef:
    name: acme-issuer
  dnsNames:
  - $DNS_NAMES
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - $DOMAINS
