# A Kubernetes ConfigMap providing the configuration-as-code
# default config for Kubernetes plugin and an example job
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-configuration-as-code
data:
  configuration-as-code.yaml: |
    jenkins:
      systemMessage: "Altorumleren Cloud Automation: configured automatically with configuration as code plugin\n\n"
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
      maven:
        installations:
        - name: "Maven 3"
          properties:
          - installSource:
              installers:
                - maven:
                    id: "3.5.4"
    jobs:
      - script: >
          pipelineJob('pipeline') {
              definition {
                  cpsScm {
                      scriptPath 'Jenkinsfile'
                      scm {
                        git {
                            remote { url 'https://github.com/mkrzyzanowski/blog-001.git' }
                            branch '*/docker-for-mac'
                            extensions {}
                        }
                      }
                  }
              }
          }
